### ISSUE TITLE
Head on svelte 5 remove css from head

### ISSUE THREAD

**Issue by stephanedemotte** [datocms/datocms-svelte#10]
Hello i'm trying to use Head on a svelte 5 project, but the Head component seem to replace all the css injected by svelte/vite.

Thank

**Comment by stefanoverna** [comment]
Hi, the [Head component](https://github.com/datocms/datocms-svelte/blob/main/src/lib/components/Head/Head.svelte) simply renders some `title` and `meta` tags.. do you have a repo that reproduces the issue?

**Comment by stephanedemotte** [comment]
Please add support for svelte 5

<img width="1396" alt="Screenshot 2024-09-23 at 14 25 50" src="https://github.com/user-attachments/assets/62e9c398-6208-4968-a32f-d4dcbb8d23a1">
<img width="1536" alt="Screenshot 2024-09-23 at 14 26 21" src="https://github.com/user-attachments/assets/049d63a4-b850-4442-8031-dda6dbbd81e9">

**Comment by stefanoverna** [comment]
Svelte 5 is still in beta, our policy is to release support upon reaching official stability :/

**Comment by stephanedemotte** [comment]
It's no more on beta but in release candidate since april 2024 https://svelte.dev/blog/svelte-5-release-candidate
Thank you !

**Comment by stefanoverna** [comment]
I see, thanks! We can try releasing a new version supporting the RC.. but to proceed it would be great if you could share a repo using Svelte v5 that reproduces the issue on the Head component you were mentioning.

Thanks!

**Comment by stefanoverna** [comment]
Any news @stephanedemotte?

**Comment by stefanoverna** [comment]
Just released @datocms/svelte v4.0.0, which supports both Svelte 5 and 4, and drops support for Svelte < 4. Nothing changes on the API.

We also upgraded our SvelteKit starter kit, which now uses v5 and runes:
https://www.datocms.com/marketplace/starters/sveltekit-starter-kit

If anyone encounters issues, please let us know, thanks!

**Comment by stephanedemotte** [comment]
@stefanoverna sorry for the delay, i cannot reproduce the bug anymore, thank for the v4 !
