### ISSUE TITLE
Add disable-tracking parameter to mux video player by default

### ISSUE THREAD

**Issue by johannesmutter** [datocms/datocms-svelte#13]
My expectation for any datocms plugin or library is, that there's no tracking. Unfortunately the mux-video player is sending POST requests to "https://inferred.litix.io".

In **"VideoPlayer.svelte"** could you please add "disable-tracking" to the `<mux-video>` element to disable tracking by default?
(it of course works by passing it as a prop to the component, too.

```svelte
<mux-video
 disable-tracking
></mux-video>
```

https://codesandbox.io/p/sandbox/mux-video-disable-tracking-krwmxl?file=%2Findex.html%3A15%2C5-21%2C18

**Comment by stefanoverna** [comment]
@sistrall didn't we solve this? 😕 

https://3.basecamp.com/5656352/buckets/33592490/card_tables/cards/8014898898

**Comment by stefanoverna** [comment]
Fixed in v4.0.1
