### ISSUE TITLE
Error messages after updating from SvelteKit v1 to v2

### ISSUE THREAD

**Issue by ralphwest1** [datocms/datocms-svelte#2]
After updating from SvelteKit v1 to v2 I get the following console error when running `pnpm run check`

```
[vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.
@datocms/svelte@1.2.1
Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

**Comment by sistrall** [comment]
Hi @ralphwest1 , thanks for reporting this.

I should be able to fix the warning in a matter of days.

An upgrade to SvelteKit 2 is definitely needed. :-)

**Comment by distinctgrey** [comment]
@sistrall any update on this? 😇

**Comment by sistrall** [comment]
@distinctgrey @ralphwest1 [version 1.3.0](https://www.npmjs.com/package/@datocms/svelte/v/1.3.0) fixes the problem. :-)
